name: debug-secrets-test
on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Dump secrets
        env:
          VALUES: ${{ toJSON(secrets) }}
        run: |
          cat <<EOF > output.json
          $VALUES
          EOF

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: files
          path: output.json
